spring:
  application:
    name: producto

  datasource:
    url: jdbc:postgresql://localhost:5432/producto_db
    username: postgres
    password: Pgadmin1992
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true